do_token = "........"
//my_ssh_devops    = "....."
another          = "......."
ssh_fingerprint  = "......"
aws_access_key   = "....."
aws_secret_key   = "....."
my_ssh_dkocheto1 = "/home/inblade/.ssh/id_rsa"
