---
# tasks file for nginx-vhosts

- name: Generate virtual_host HTTP
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    mode=0644
  loop:
    -  { src: 'host1.j2' , dest: '{{ virtual_hosts_folder_remote }}/{{ domain_name }}.conf'}
    -  { src: 'host2.j2' , dest: '{{ virtual_hosts_folder_remote }}/{{ domain_name }}.conf'}
  notify: Reload nginx
