---
# defaults file for nginx-vhosts

nginx_log_folder_remote: /var/log/nginx
nginx_config_remote: /etc/nginx
virtual_hosts_folder_remote: /etc/nginx/conf.d
site_folder_remote: /home
domain_name: dkocheto.devops.rebrain.srwx.net
